# Generated by Django 4.2.3 on 2023-08-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='WhichBooksDoYouLikeToRead',
            field=models.TextField(blank=True, db_column='anvar_WhichBooksDoYouLikeToRead'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='WhichBooksDoYouLikeToRead',
            field=models.TextField(blank=True, db_column='anvar_WhichBooksDoYouLikeToRead'),
        ),
    ]
