# Generated by Django 4.2.3 on 2023-10-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_student_date_volunteer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='WhatLevelofSkillDoYouHaveInCulturalActivity',
            field=models.TextField(blank=True, db_column='anvar_WhatLevelofSkillDoYouHaveInCulturalActivity'),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='WhatLevelofSkillDoYouHaveInCulturalActivity',
            field=models.TextField(blank=True, db_column='anvar_WhatLevelofSkillDoYouHaveInCulturalActivity'),
        ),
    ]
